name: flutter_learning_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  google_fonts: ^1.1.1
  http: ^0.12.2
  image_picker: ^0.6.7+21
  intl_phone_field: ^1.4.2
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
